# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-27 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='userwishlist',
            name='user',
            field=models.ManyToManyField(related_name='wishes', to='wishlist.User'),
        ),
    ]
